//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/InputAcctionsControllers.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputAcctionsControllers: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputAcctionsControllers()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputAcctionsControllers"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""a9f0d106-725b-4c0e-9bee-eb01fdbe22a5"",
            ""actions"": [
                {
                    ""name"": ""DFJK"",
                    ""type"": ""Value"",
                    ""id"": ""861d96e2-48df-4f35-9722-b219790c68ca"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""6999099a-2201-4084-826f-9ce8a7466070"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Flechas"",
                    ""type"": ""Button"",
                    ""id"": ""a0bb671f-3384-4450-b4e8-1066da421071"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AWSD"",
                    ""type"": ""Button"",
                    ""id"": ""747525f2-8bde-4da6-9a06-fa5a31062fda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8c5c405b-2e15-48f9-ab80-0e98efc7eb64"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DFJK"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""079e88e0-62ef-44e1-81c0-ead05686836e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DFJK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3ce7a85c-34f4-4e67-9490-4997d48b92b9"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DFJK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""55292b8c-f91d-41fa-b39f-11376c9913c3"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DFJK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b7c569e1-eacf-42dd-945b-d55daec98a25"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DFJK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4b1fd7d6-df69-4154-85a8-8e420a64480c"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd7adddd-977c-480a-9ffc-4beff8e38ca0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flechas"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a609c4b5-5458-4d6d-b5be-dfd292e3e8af"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flechas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""11b67b4e-4df1-4fc5-9843-4d50cd5cef74"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flechas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""084acf30-25fa-40cd-b456-1b35ddfd83a1"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flechas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a3090ce5-44e8-4f90-ac5b-6ba5e2cc4057"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flechas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a9369298-2caa-4368-ae3e-eef30525b71e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AWSD"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""df1206a0-6b58-4b85-8264-f23c39e2c3a5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AWSD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""59d2498d-8ce3-4b86-b7f0-2720350b09fa"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AWSD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""878684f6-f674-4685-a735-c8561e606d71"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AWSD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""478ea045-ea65-4dcf-a6e7-8b7b97e3f1a8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AWSD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Acciones"",
            ""id"": ""5876161d-8ade-4fe0-b14f-2fb6262f3257"",
            ""actions"": [
                {
                    ""name"": ""Seleccionar"",
                    ""type"": ""Button"",
                    ""id"": ""81fba080-b878-4fc4-8ef1-85bbefd23eaa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Salir"",
                    ""type"": ""Button"",
                    ""id"": ""a6ed858f-70fb-4b14-ac52-c9ed5cbc0412"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Desplazar"",
                    ""type"": ""Value"",
                    ""id"": ""d2bfd7e4-05a0-46c3-aff3-ee4876f0ba17"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""831cdd2a-b107-455d-8b72-a0ac8ba0f892"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Seleccionar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3d36c00-395a-446a-af0f-3d3b11d7b0eb"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Seleccionar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b56a09d-9426-4f64-85ad-bbcc58389836"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Salir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0307e703-9468-47e6-84bb-5e96a23c8c2c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Desplazar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d3a47890-1d97-4052-ada8-e5bc50f52ad4"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Desplazar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1516895f-6c59-4873-8606-849f79a62e41"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Desplazar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Game
        m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
        m_Game_DFJK = m_Game.FindAction("DFJK", throwIfNotFound: true);
        m_Game_Pause = m_Game.FindAction("Pause", throwIfNotFound: true);
        m_Game_Flechas = m_Game.FindAction("Flechas", throwIfNotFound: true);
        m_Game_AWSD = m_Game.FindAction("AWSD", throwIfNotFound: true);
        // Acciones
        m_Acciones = asset.FindActionMap("Acciones", throwIfNotFound: true);
        m_Acciones_Seleccionar = m_Acciones.FindAction("Seleccionar", throwIfNotFound: true);
        m_Acciones_Salir = m_Acciones.FindAction("Salir", throwIfNotFound: true);
        m_Acciones_Desplazar = m_Acciones.FindAction("Desplazar", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game
    private readonly InputActionMap m_Game;
    private List<IGameActions> m_GameActionsCallbackInterfaces = new List<IGameActions>();
    private readonly InputAction m_Game_DFJK;
    private readonly InputAction m_Game_Pause;
    private readonly InputAction m_Game_Flechas;
    private readonly InputAction m_Game_AWSD;
    public struct GameActions
    {
        private @InputAcctionsControllers m_Wrapper;
        public GameActions(@InputAcctionsControllers wrapper) { m_Wrapper = wrapper; }
        public InputAction @DFJK => m_Wrapper.m_Game_DFJK;
        public InputAction @Pause => m_Wrapper.m_Game_Pause;
        public InputAction @Flechas => m_Wrapper.m_Game_Flechas;
        public InputAction @AWSD => m_Wrapper.m_Game_AWSD;
        public InputActionMap Get() { return m_Wrapper.m_Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void AddCallbacks(IGameActions instance)
        {
            if (instance == null || m_Wrapper.m_GameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameActionsCallbackInterfaces.Add(instance);
            @DFJK.started += instance.OnDFJK;
            @DFJK.performed += instance.OnDFJK;
            @DFJK.canceled += instance.OnDFJK;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Flechas.started += instance.OnFlechas;
            @Flechas.performed += instance.OnFlechas;
            @Flechas.canceled += instance.OnFlechas;
            @AWSD.started += instance.OnAWSD;
            @AWSD.performed += instance.OnAWSD;
            @AWSD.canceled += instance.OnAWSD;
        }

        private void UnregisterCallbacks(IGameActions instance)
        {
            @DFJK.started -= instance.OnDFJK;
            @DFJK.performed -= instance.OnDFJK;
            @DFJK.canceled -= instance.OnDFJK;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Flechas.started -= instance.OnFlechas;
            @Flechas.performed -= instance.OnFlechas;
            @Flechas.canceled -= instance.OnFlechas;
            @AWSD.started -= instance.OnAWSD;
            @AWSD.performed -= instance.OnAWSD;
            @AWSD.canceled -= instance.OnAWSD;
        }

        public void RemoveCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameActions instance)
        {
            foreach (var item in m_Wrapper.m_GameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameActions @Game => new GameActions(this);

    // Acciones
    private readonly InputActionMap m_Acciones;
    private List<IAccionesActions> m_AccionesActionsCallbackInterfaces = new List<IAccionesActions>();
    private readonly InputAction m_Acciones_Seleccionar;
    private readonly InputAction m_Acciones_Salir;
    private readonly InputAction m_Acciones_Desplazar;
    public struct AccionesActions
    {
        private @InputAcctionsControllers m_Wrapper;
        public AccionesActions(@InputAcctionsControllers wrapper) { m_Wrapper = wrapper; }
        public InputAction @Seleccionar => m_Wrapper.m_Acciones_Seleccionar;
        public InputAction @Salir => m_Wrapper.m_Acciones_Salir;
        public InputAction @Desplazar => m_Wrapper.m_Acciones_Desplazar;
        public InputActionMap Get() { return m_Wrapper.m_Acciones; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AccionesActions set) { return set.Get(); }
        public void AddCallbacks(IAccionesActions instance)
        {
            if (instance == null || m_Wrapper.m_AccionesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AccionesActionsCallbackInterfaces.Add(instance);
            @Seleccionar.started += instance.OnSeleccionar;
            @Seleccionar.performed += instance.OnSeleccionar;
            @Seleccionar.canceled += instance.OnSeleccionar;
            @Salir.started += instance.OnSalir;
            @Salir.performed += instance.OnSalir;
            @Salir.canceled += instance.OnSalir;
            @Desplazar.started += instance.OnDesplazar;
            @Desplazar.performed += instance.OnDesplazar;
            @Desplazar.canceled += instance.OnDesplazar;
        }

        private void UnregisterCallbacks(IAccionesActions instance)
        {
            @Seleccionar.started -= instance.OnSeleccionar;
            @Seleccionar.performed -= instance.OnSeleccionar;
            @Seleccionar.canceled -= instance.OnSeleccionar;
            @Salir.started -= instance.OnSalir;
            @Salir.performed -= instance.OnSalir;
            @Salir.canceled -= instance.OnSalir;
            @Desplazar.started -= instance.OnDesplazar;
            @Desplazar.performed -= instance.OnDesplazar;
            @Desplazar.canceled -= instance.OnDesplazar;
        }

        public void RemoveCallbacks(IAccionesActions instance)
        {
            if (m_Wrapper.m_AccionesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAccionesActions instance)
        {
            foreach (var item in m_Wrapper.m_AccionesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AccionesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AccionesActions @Acciones => new AccionesActions(this);
    public interface IGameActions
    {
        void OnDFJK(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnFlechas(InputAction.CallbackContext context);
        void OnAWSD(InputAction.CallbackContext context);
    }
    public interface IAccionesActions
    {
        void OnSeleccionar(InputAction.CallbackContext context);
        void OnSalir(InputAction.CallbackContext context);
        void OnDesplazar(InputAction.CallbackContext context);
    }
}
